### ISSUE TITLE
How can I improve the stability or smoothness of the  face mesh tracker?

### ISSUE THREAD

**Issue by jizefeng0810** [ndonkoHenri/Face_Mesh_Detector_and_Tracker#1]
A good job! 
How can I improve the stability or smoothness of the  face mesh tracker?

**Comment by ndonkoHenri** [comment]
**This depends mainly on your machine's performances(GPU/CPU).**
The FPS(frames per second) displayed at the top-left section of the screen, is a measure of the number of frames showed every second. 
Logically speaking,
**The higher the computer performances, the higher the FPS and the smoother/better the result.**
